import { CloudProviderConfig } from "@/types/provider.types";

export const CLOUD_PROVIDERS: CloudProviderConfig[] = [
  {
    id: "aws",
    name: "Amazon Web Services",
    shortName: "AWS",
    category: "Cloud Hyperscaler",
    status: "Production-Ready",
    badge: "PRODUCTION-READY",
    badgeBg: "bg-emerald-100 text-emerald-900 border-emerald-300",
    brandColor: "#FF9900",
    defaultRegion: "ap-south-1",
    supportedRegions: ["ap-south-1", "us-east-1", "us-west-2", "eu-central-1", "ap-southeast-1"],
    resources: [
      "AWS Lambda (Node.js 22/Arm64)",
      "Amazon Aurora PostgreSQL v2",
      "Amazon S3 Storage Buckets",
      "Amazon SQS Queues",
      "API Gateway HTTP v2",
      "IAM Least-Privilege Roles",
    ],
    desc: "Full production target compiler generating scoped IAM policies and deterministic CloudFormation/CDK execution plans.",
    docUrl: "/docs/concepts/providers",
  },
  {
    id: "azure",
    name: "Microsoft Azure",
    shortName: "Azure",
    category: "Enterprise Cloud",
    status: "Production-Ready",
    badge: "PRODUCTION-READY",
    badgeBg: "bg-emerald-100 text-emerald-900 border-emerald-300",
    brandColor: "#0089D6",
    defaultRegion: "centralindia",
    supportedRegions: ["centralindia", "eastus", "westeurope", "southeastasia"],
    resources: [
      "Azure Container Apps",
      "Azure Cosmos DB / Postgres",
      "Azure Blob Storage",
      "Azure Event Grid",
      "Azure API Management",
    ],
    desc: "Enterprise cloud target emitting ARM and Bicep manifests with Azure Active Directory zero-trust credentials.",
    docUrl: "/docs/concepts/providers",
  },
  {
    id: "cloudflare",
    name: "Cloudflare Edge",
    shortName: "Cloudflare",
    category: "Global Edge Network",
    status: "Production-Ready",
    badge: "PRODUCTION-READY",
    badgeBg: "bg-emerald-100 text-emerald-900 border-emerald-300",
    brandColor: "#F38020",
    defaultRegion: "320 Edge PoPs",
    supportedRegions: ["320 Edge PoPs Global", "North America", "Europe", "Asia-Pacific"],
    resources: [
      "Cloudflare Workers (V8 Isolates)",
      "Workers KV Key-Value Store",
      "Cloudflare R2 Object Storage",
      "Cloudflare Queues",
      "Hyperdrive Postgres Proxy",
    ],
    desc: "High-performance edge target emitting sub-4ms V8 isolate worker bundles and global KV replication.",
    docUrl: "/docs/concepts/providers",
  },
  {
    id: "kubernetes",
    name: "Kubernetes (K8s)",
    shortName: "Kubernetes",
    category: "Container Orchestration",
    status: "Production-Ready",
    badge: "PRODUCTION-READY",
    badgeBg: "bg-emerald-100 text-emerald-900 border-emerald-300",
    brandColor: "#326CE5",
    defaultRegion: "k8s-cluster-prod",
    supportedRegions: ["EKS Cluster", "AKS Cluster", "GKE Cluster", "Local Kind"],
    resources: [
      "Kubernetes Deployments & Pods",
      "K8s Services & ClusterIP",
      "Ingress Controller (NGINX/Traefik)",
      "ConfigMaps & K8s Secrets",
      "StatefulSets & PersistentVolumes",
    ],
    desc: "Compiles microservices into production-ready Kubernetes declarative manifests and Helm charts.",
    docUrl: "/docs/concepts/providers",
  },
  {
    id: "docker",
    name: "Docker Containers",
    shortName: "Docker",
    category: "OCI Runtime",
    status: "Production-Ready",
    badge: "PRODUCTION-READY",
    badgeBg: "bg-emerald-100 text-emerald-900 border-emerald-300",
    brandColor: "#2496ED",
    defaultRegion: "Local Daemon",
    supportedRegions: ["Docker Engine", "Docker Compose v2", "ECR / ACR / DockerHub"],
    resources: [
      "Multi-stage OCI Container Images",
      "Docker Compose v2 Stack",
      "Local Volume Mounts",
      "Bridge & Overlay Networks",
    ],
    desc: "Builds minimal, hardened OCI container images with multi-stage caching for seamless local and serverless execution.",
    docUrl: "/docs/concepts/providers",
  },
  {
    id: "terraform",
    name: "Terraform / OpenTofu",
    shortName: "Terraform",
    category: "IaC Compatibility",
    status: "Production-Ready",
    badge: "COMPATIBILITY",
    badgeBg: "bg-purple-100 text-purple-900 border-purple-300",
    brandColor: "#844FBA",
    defaultRegion: "HCL Export",
    supportedRegions: ["HCL v1.5+", "Terraform Cloud", "OpenTofu 1.8+"],
    resources: [
      "HCL Module Generator",
      "State Migration Engine",
      "Zero-Drift Plan Verification",
      "Terraform Provider Bindings",
    ],
    desc: "Seamlessly export Nova IR blueprints directly into canonical Terraform/OpenTofu HCL modules for enterprise pipelines.",
    docUrl: "/docs/concepts/providers",
  },
  {
    id: "local",
    name: "Local Development Emulator",
    shortName: "Local Sandbox",
    category: "Developer Sandbox",
    status: "Production-Ready",
    badge: "SUB-200MS",
    badgeBg: "bg-emerald-100 text-emerald-900 border-emerald-300",
    brandColor: "#10B981",
    defaultRegion: "localhost:3000",
    supportedRegions: ["Localhost", "LAN Network", "CI/CD Test Runner"],
    resources: [
      "Hono HTTP Fast Sandbox",
      "Local S3 Storage Bucket Mock",
      "Local SQS Queue Simulator",
      "In-Memory SQLite / Postgres Mock",
    ],
    desc: "Instant sub-200ms development server running entirely on your local workstation with zero cloud credentials required.",
    docUrl: "/docs/cli/dev",
  },
  {
    id: "gcp",
    name: "Google Cloud Platform",
    shortName: "GCP",
    category: "Hyperscale Cloud",
    status: "Planned Roadmap",
    badge: "PLANNED ROADMAP",
    badgeBg: "bg-gray-100 text-gray-800 border-gray-300",
    brandColor: "#4285F4",
    defaultRegion: "asia-south1",
    supportedRegions: ["asia-south1", "us-central1", "europe-west1"],
    resources: [
      "GCP Cloud Run Services",
      "Google Cloud Storage (GCS)",
      "Cloud Pub/Sub Topics",
      "Cloud SQL Postgres",
    ],
    desc: "Planned provider adapter on our multi-cloud roadmap for Cloud Run and GCP Pub/Sub mapping.",
    docUrl: "/docs/concepts/providers",
  },
];

export function getProviderConfig(id: string): CloudProviderConfig | undefined {
  return CLOUD_PROVIDERS.find((p) => p.id === id);
}
